### ISSUE TITLE
Formatting BRT PG references

### ISSUE THREAD

**Issue by dcpaschall** [ITDP/the-online-brt-planning-guide#102]
Each chapter is different regarding references. Some chapters have many, some chapters have a few, and some chapters don't have any references at all. We were thinking of citing in-text for the chapters that have just a few references, and then we were wondering if we should include a references page at the end each chapter that has many references. Does that make sense and sound feasible? Thanks! -Daniel

**Comment by jonasmalacofilho** [comment]
That does make sense to me; but @aszasz is more familiar than me with the issue...

**Comment by aszasz** [comment]
@jonasmalacofilho : I do not know what is feasible... and I don't know what makes sense either... 

disclaimer below considered: 

I like the wikipedia on this matter (it is a foot note mark hyper link to the end of the page, but you don't need to click... it shows when you hover), but that does not work with the section structure we have, because we don't want sections' references, but chapters.

I also like uniformity: so I would suggest creating a reference section for all chapters that have references (even if it is only one), if the text says see reference 1, it is not even necessary to make the link (one knows where to look).

DISCLAIMER:
I learned reading in a time where references were useful only to learn peoples names and notice that the author liked one or the other...  even if I was at the library, it was very unlikely I would find the referred to book or information about it (and English was way more difficult for me than today), my technical readings were defined by personal recommendation, which needed to come with answer to ' where can I find this book? if a xerox of the important pages available, it would be even better'... so I developed indifference towards references, this is not to say that I don't like them (they are difficult to read with all those rules and weird abreviations... et all ....  I like links to source!)

**Comment by jonasmalacofilho** [comment]
A references `\section` would be a great solution, I think.  Not sure though if all references must live in appropriate sections.

How about the format used for the reference (in the section).  What would be a representative example?

---

*Not really suggesting this (it was never in the plans), but...*

*For chapters with few references, of simply for short citations, maybe footnotes could be great.  And it shouldn't be terribly hard, technically, to add them...*

*On the other hand, we do have the `\quotation` element.  In fact, if I remember correctly, this was one of the reasons why footnotes were left out (the other one being the fact that there weren't many of them, maybe not even one).*

**Comment by jonasmalacofilho** [comment]
Adding "bibliography" sections seems to work well, so I'll close the issue.
