### ISSUE TITLE
Author formatting 

### ISSUE THREAD

**Issue by aegauthier** [ITDP/the-online-brt-planning-guide#105]
Hi - 

So, maybe it would be good for the contributors to be italicized text. I was thinking about a box but thought it would visually be too much clutter? Am open to other ideas.

Also, I would like to have a hard stop after Contributors: and the names so instead of being like this
Contributors: Aimee Gauthier
it would look like
Contributors:
Aimee Gauthier

but i can do that later. 

Let me know your thoughts. Thanks

**Comment by dcpaschall** [comment]
Could we have the authors' names in a sans serif font and in the same color as the title's color? And we are thinking that maybe it would be good to actually not italicize the authors' names, since that would be too similar to the italicized quoted text below the authors.

**Comment by aszasz** [comment]
@craice, can you figure out a nice style for this? Authors are on #100 that shall be merged soon.

**Comment by aszasz** [comment]
I was considering the alternatives:
1. demand that chapters require authors... then this would be a new parameter in
``\chapter{Title}{author(s) string}``
-- then, ff there is no author, the system rejects it. (feature very particular for this project)
2.  it would be an indepedent format that could be applied anywhere
``\contributor{authors string}``
-- then, it has a huge potential to be misused (but well used too)

@craice: drawing a volume colorful pen in the begining is feasible (aesthetically), Could use the same simbol for the images' credits?

**Comment by aszasz** [comment]
I briefly talk to Jonas (he starts traveling back today) and present here what he told me and I agree (the part I don't I let him do it :sweat_smile: ): like everything else we did thus far...  this has to be well thought before insertion. It is an impacting feature to the language.

Check variants that do not require the feature on pull #100 ([live!](https://brt.robrt.io/pull_request/100/guide/traffic-impact-assessment/index.html))

**Comment by jonasmalacofilho** [comment]
This has a an apparently ok solution for the moment, so I'll label this low-priority.

I would add to the discussion that maybe we should first discuss exactly who are the "contributors"...  Is the list exhaustive?  Anyone with a reasonable contribution (in authorship, revision, editing of something else) could become a "listed" contributor?

I ask this because styling should match these definitions; for example, if the list isn't exhaustive, a highlighted structured element might not be such a good idea.

**Comment by aegauthier** [comment]
Okay - I am feeling dumb and not able to see the variations, but what i see online looks okay, especially for now.

Contributors: it is tricky because some chapters are written from scratch and some are light revisions to the old Volume 3 text and some fall in between. The third edition didn't attribute.  So I couldn't say with authority who authors were for many chapters, so I am using contributors. But then many of the chapters are collaborative or ITDP staff significantly rewrote or edited them. So the what I have done it is to include main people first - either the authors or significant contributors, then heavy editors and then the peer reviewers (lighter reviews / edits). it is mostly exhaustive. does that make sense?

**Comment by jonasmalacofilho** [comment]
Yeah, got it!

Well, I had an idea of something a bit more general (I was thinking about solutions to another issue, but I can't remember what it was right now): an equivalent to the `\highlight` command (that works on words or _horizontal elements_) for an entire paragraph.

Maybe we could call it `\notice`.  In my mind, it could indeed be styled in a similar way as a box, but it would have no name or number associated with it.

Still, given that what we have works for now, and that I can't remember what the other use case was, I'll keep this in my mind but wont act on it immediately.  Also, maybe all we need (for this or the other case) is a box.

---

@aegauthier you won't be able to see the variations anymore, since the pull request was updated after that and we only keep the latest generated website & pdf for each branch/pull request.  _(the logs, we keep them all)_

Each build was resulting in 1.4 GiB!  I already reduced that in half, and #109 should further reduce that much again, but 350 MiB still is a lot of data to keep for every single push.  _(technical solutions exist – essentially, saving them on Amazon S3 – but maybe there aren't that necessary... we can usually just open another PR and have that snapshot of the guide regenerated)_

**Comment by thaiscmlima** [comment]
@aegauthier me and Jonas discussed and agreed today that authors' list can be displayed on the bottom of the overview page; otherwise it's too close the quote and take some focus away from it. Please let us know if we can go forward this way.

**Comment by aszasz** [comment]
@aegauthier let me know if you want me to make a PR (pull request) with the snapshots of the alternative contributors styles, so you can compare them.

**Comment by jonasmalacofilho** [comment]
I'm going to close this since everybody agrees that the current solution is pretty good.

Still, I've pushed a minor improvement in 87767bd25a1ca4e2ca27a3c3e073f4455caef457...  (we can revert it later, if necessary)
