### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by aegauthier** [ITDP/the-online-brt-planning-guide#145]
Hi -

I wanted to ask about being able to search a whole chapter (i.e. child pages, etc.) - I wanted to search a chapter for something, but I could only do it page by page which was enormously inefficient so I went back to the Word version to do it. It was also chapter 6 - the baddest one of them all : ) - so just wanted to ask about that.

Thanks - Aimee

**Comment by jonasmalacofilho** [comment]
Hi!

This is something we're looking into!  
(we've been discussing this with @thaiscmlima)

In the mean time, here are the workarounds we've been using:
 - Google search with a `site` filter; e.g.  
[`limited stop services site:brtguide.itdp.org`](https://www.google.com.br/#q=limited+stop+services+site:brtguide.itdp.org)
 - GitHub search through the manuscript files in the repository, using a `extension` filter; e.g.  
[`limited stop services extension:manu`](https://github.com/ITDP/the-online-brt-planning-guide/search?utf8=%E2%9C%93&q=limited+stop+services+extension%3Amanu&type=)
 - Local search through the manuscript files (this requires a local copy of the repository)

P.S. ~We'll soon add a~ We've since added some configurations to prevent branches other than master and internal files from appearing in the search results.  This ~will (soon propagate fully and) eliminate~ eliminates the need for `/branch/master/guide` in the `site` filter).

**Comment by aegauthier** [comment]
great - thanks

**Comment by craice** [comment]
**mockup:**

![brt_search_test_001](https://user-images.githubusercontent.com/5419183/27291488-b586ef28-54e6-11e7-835e-960f351d2391.png)

**html:**

```
(...)
<header>
  <ul>
    (...)
    <li class="search">
      <form>
        <input type="text" placeholder="Search...">
      </form>
    </li>
  </ul>
  (...)
</header>
(...)
```

**css:**

```
li.search {
  float: right;
  padding: 0;
}
li.search input {
  height: 32px;
  width: 238px;
  background-color: #EEEEEE;
  padding: 0 8px;
  font-family: 'PT Sans';
  font-size: 14px;
  background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAYZJREFUeNrsV9GNgkAQxcv9awfagRoKkA7cDqQEroKzBErADqADrgAS7EA7OCvgZpO3l8kGFlYGzV2cZAPLLszbmfdmdNY0TfBMewuebC8A70M2VVUV0yWhsbaWChp5GIbZvQBmLhKS4w1dshbHtn3RUATkWwwAnJc05nh0Bpga84iGjsySrUe+IFwpyJjzD/pwaq1rcEcCqvcdECV9r0aTEDlfO5z/Gq3pvSdM9/RuJKGCBNery7m1/4b7WAKAOf0Q5wHynjFuiNWB2uNbhnzLf1UJfcK5YnIcDaDwIRQxf8HkV0oAyE0+ofM+4zUj9QHgqoT6JDtMtc4Tu8rh5Nr5nsl2JQVggXAaSd4QmQvLuWInlwXQccIhdkJ1HA+AATGNZ8MicmaEUy36LwiIEgEwUAVlS9vujYZIIQI585alA4E7PqoSXjqef6K7TpeCDunatqVI1VP3AuUoxenkzQhciNlvg94UiXdDhDlylPfpOGDxQSEaWqIpAXssgNdfsz8D4EeAAQBPDprQo6JCrgAAAABJRU5ErkJggg==');
  background-repeat: no-repeat;
  background-position-x: right;
  border-width: 0 1px;
  border-color: #00a95e;
  border-style: solid;
}
```
